	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.14.1/build/cssreset/cssreset-min.css">
	<link type="text/css" rel="stylesheet" href="clearfix.css"/>
	<link rel="stylesheet" type="text/css" href="homepagestylesheet.css">
	<link type="text/css" rel="stylesheet" href="employmentstylesheet.css"/>
	<link type="text/css" rel="stylesheet" href="servicesstylesheet.css"/>
	<link type="text/css" rel="stylesheet" href="contactsstylesheet.css"/>
	<link type="text/css" rel="stylesheet" href="faqstylesheet.css"/>
	<link type="text/css" rel="stylesheet" href="productsstylesheet.css"/>
	<title><?php echo $title ?></title>